<?php

/**
 * Implements hook_form_form_alter();
 */
function yoast_seo_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#after_build']) && !empty($form['#after_build'])) {
    $form['#after_build'][] = 'yoast_seo_form_node_afterbuild' ;
  } else {
    $form['#after_build'] = [ 'yoast_seo_form_node_afterbuild' ];
  }
}


/**
 * Implements hook_views_pre_view();
 * Add field_yoast_seo in the content views.
 */
function yoast_seo_views_pre_view($view, $display_id, array &$args) {
  if ($view->id() == 'content') {

    $handlers = $view->getHandlers('field', $display_id);
    if (!isset($handlers['field_yoast_seo'])) {
      $view->addHandler(
        $display_id,
        'field',
        'node__field_yoast_seo',
        'field_yoast_seo',
        [
          'type' => 'yoastseo_formatter',
        ]
      );
      $view->save();
    }
  }
}

/**
 * After build function.
 * Reads the form, and deduct associated yoastseo configuration from it.
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function yoast_seo_form_node_afterbuild(&$form, $form_state) {
  if (isset($form['field_yoast_seo'])) {
    $yoast_seo_field_manager = \Drupal::service('yoast_seo.field_manager');
    $form = $yoast_seo_field_manager->setFieldsConfiguration($form);
    $form = $yoast_seo_field_manager->addSnippetEditorMarkup($form);
    $form = $yoast_seo_field_manager->addOverallScoreMarkup($form);
  }

  return $form;
}

/**
 * Implements hook_theme().
 */
function yoast_seo_theme() {
  $theme['snippet'] = [
    'variables' => [
      'wrapper_target_id' => NULL,
      'snippet_target_id' => NULL,
      'output_target_id' => NULL,
    ],
    'template' => 'snippet',
  ];

  $theme['overall_score'] = [
    'variables' => [
      'overall_score_target_id' => NULL,
      'overall_score' => NULL,
    ],
    'template' => 'overall_score',
  ];

  $theme['content_score'] = [
    'variables' => [

    ],
    'template' => 'content_score',
  ];

  return $theme;
}
